/*
 * generated by Xtext
 */

package org.sourcepit.java.literals.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * Represents a generated, default implementation of superclass
 * {@link org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider}.
 * Methods are dynamically dispatched on the first parameter, i.e., you can override them
 * with a more concrete subtype.
 */
@SuppressWarnings("all")
public class AbstractLiteralsProposalProvider
   extends
      org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider {

   public void completeIntegerLiteral_Value(EObject model, Assignment assignment, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      completeRuleCall(((RuleCall) ((Alternatives) assignment.getTerminal()).getElements().get(0)), context, acceptor);
      completeRuleCall(((RuleCall) ((Alternatives) assignment.getTerminal()).getElements().get(1)), context, acceptor);
      completeRuleCall(((RuleCall) ((Alternatives) assignment.getTerminal()).getElements().get(2)), context, acceptor);
      completeRuleCall(((RuleCall) ((Alternatives) assignment.getTerminal()).getElements().get(3)), context, acceptor);
   }

   public void completeFloatingPointLiteral_Value(EObject model, Assignment assignment, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      completeRuleCall(((RuleCall) ((Alternatives) assignment.getTerminal()).getElements().get(0)), context, acceptor);
      completeRuleCall(((RuleCall) ((Alternatives) assignment.getTerminal()).getElements().get(1)), context, acceptor);
   }

   public void completeBooleanLiteral_Value(EObject model, Assignment assignment, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      completeRuleCall(((RuleCall) ((Alternatives) assignment.getTerminal()).getElements().get(0)), context, acceptor);
      completeRuleCall(((RuleCall) ((Alternatives) assignment.getTerminal()).getElements().get(1)), context, acceptor);
   }

   public void completeCharacterLiteral_Value(EObject model, Assignment assignment, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      completeRuleCall(((RuleCall) assignment.getTerminal()), context, acceptor);
   }

   public void completeStringLiteral_Value(EObject model, Assignment assignment, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      completeRuleCall(((RuleCall) assignment.getTerminal()), context, acceptor);
   }

   public void completeNullLiteral_Value(EObject model, Assignment assignment, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      completeRuleCall(((RuleCall) assignment.getTerminal()), context, acceptor);
   }

   public void complete_Foo(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_literal(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_IntegerLiteral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_DecimalIntegerLiteral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_HexIntegerLiteral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_OctalIntegerLiteral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_BinaryIntegerLiteral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_IntegerTypeSuffix(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_DecimalNumeral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_NonZeroDigit(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_Digits(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_Digit(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_DigitsAndUnderscores(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_DigitOrUnderscore(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_Underscores(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_HexNumeral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_HexDigits(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_HexDigit(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_HexDigitsAndUnderscores(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_HexDigitOrUnderscore(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_OctalNumeral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_OctalDigits(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_OctalDigit(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_OctalDigitsAndUnderscores(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_OctalDigitOrUnderscore(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_BinaryNumeral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_BinaryDigits(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_BinaryDigit(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_BinaryDigitsAndUnderscores(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_BinaryDigitOrUnderscore(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_FloatingPointLiteral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_DecimalFloatingPointLiteral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_ExponentPart(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_ExponentIndicator(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_SignedInteger(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_SIGN(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_FloatTypeSuffix(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_HexadecimalFloatingPointLiteral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_HexSignificand(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_BinaryExponent(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_BinaryExponentIndicator(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_BooleanLiteral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_TRUE(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_FALSE(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_CharacterLiteral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_CHARACTER(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_StringLiteral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_STRING(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_EscapeSequence(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_OctalEscape(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_ZeroToThree(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_UnicodeEscape(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_UnicodeMarker(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_NullLiteral(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_NULL(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_Identifier(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_JavaLetter(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_JavaLetterOrDigit(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_ML_COMMENT(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_SL_COMMENT(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }

   public void complete_WS(EObject model, RuleCall ruleCall, ContentAssistContext context,
      ICompletionProposalAcceptor acceptor) {
      // subclasses may override
   }
}
