/*
 * generated by Xtext
 */
package org.sourcepit.java.type.scoping

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
class TypeScopeProvider extends org.sourcepit.java.literals.scoping.LiteralsScopeProvider {

}
