/*
 * generated by Xtext
 */

package org.sourcepit.java.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.sourcepit.java.ui.internal.JavaActivator;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class JavaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

   @Override
   protected Bundle getBundle() {
      return JavaActivator.getInstance().getBundle();
   }

   @Override
   protected Injector getInjector() {
      return JavaActivator.getInstance().getInjector(JavaActivator.ORG_SOURCEPIT_JAVA_JAVA);
   }

}
