/*
 * generated by Xtext
 */

package org.sourcepit.java.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JavaUiModule extends org.sourcepit.java.ui.AbstractJavaUiModule {
   public JavaUiModule(AbstractUIPlugin plugin) {
      super(plugin);
   }
}
