/*
 * generated by Xtext
 */
package org.sourcepit.java.ui.contentassist

import org.sourcepit.java.ui.contentassist.AbstractJavaProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class JavaProposalProvider extends AbstractJavaProposalProvider {
}
