/**
 * generated by Xtext
 */

package org.sourcepit.java.type.validation;


/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TypeValidator extends AbstractTypeValidator {
}
