/*
 * generated by Xtext
 */

package org.sourcepit.java.type.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TypeUiModule extends org.sourcepit.java.type.ui.AbstractTypeUiModule {
   public TypeUiModule(AbstractUIPlugin plugin) {
      super(plugin);
   }
}
