/*
 * generated by Xtext
 */

package org.sourcepit.java.expressions.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.sourcepit.java.expressions.ui.internal.ExpressionsActivator;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class ExpressionsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

   @Override
   protected Bundle getBundle() {
      return ExpressionsActivator.getInstance().getBundle();
   }

   @Override
   protected Injector getInjector() {
      return ExpressionsActivator.getInstance().getInjector(
         ExpressionsActivator.ORG_SOURCEPIT_JAVA_EXPRESSIONS_EXPRESSIONS);
   }

}
