/**
 * generated by Xtext
 */

package org.sourcepit.java.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class JavaQuickfixProvider extends DefaultQuickfixProvider {
}
