/*
 * generated by Xtext
 */

package org.sourcepit.java.literals;

/**
 * Initialization support for running Xtext languages
 * without equinox extension registry
 */
public class LiteralsStandaloneSetup extends LiteralsStandaloneSetupGenerated {

   public static void doSetup() {
      new LiteralsStandaloneSetup().createInjectorAndDoEMFRegistration();
   }
}
