/*
 * generated by Xtext
 */

package org.sourcepit.java.literals;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LiteralsRuntimeModule extends org.sourcepit.java.literals.AbstractLiteralsRuntimeModule {

}
