/**
 * generated by Xtext
 */

package org.sourcepit.java.expressions.scoping;

import org.sourcepit.java.literals.scoping.LiteralsScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class ExpressionsScopeProvider extends LiteralsScopeProvider {
}
