/*
 * generated by Xtext
 */

package org.sourcepit.java.parser.antlr;

import java.io.InputStream;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JavaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

   public InputStream getAntlrTokenFile() {
      ClassLoader classLoader = getClass().getClassLoader();
      return classLoader.getResourceAsStream("org/sourcepit/java/parser/antlr/internal/InternalJava.tokens");
   }
}
