/*
 * generated by Xtext
 */

package org.sourcepit.java.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.sourcepit.java.services.JavaGrammarAccess;

import com.google.inject.Inject;

public class JavaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {

   @Inject
   private JavaGrammarAccess grammarAccess;

   @Override
   protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
      tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
   }

   @Override
   protected org.sourcepit.java.parser.antlr.internal.InternalJavaParser createParser(XtextTokenStream stream) {
      return new org.sourcepit.java.parser.antlr.internal.InternalJavaParser(stream, getGrammarAccess());
   }

   @Override
   protected String getDefaultRuleName() {
      return "Model";
   }

   public JavaGrammarAccess getGrammarAccess() {
      return this.grammarAccess;
   }

   public void setGrammarAccess(JavaGrammarAccess grammarAccess) {
      this.grammarAccess = grammarAccess;
   }

}
