/**
 * generated by Xtext
 */

package org.sourcepit.java.expressions.ui.quickfix;

import org.sourcepit.java.literals.ui.quickfix.LiteralsQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class ExpressionsQuickfixProvider extends LiteralsQuickfixProvider {
}
