/**
 * generated by Xtext
 */

package org.sourcepit.java.ui.contentassist;


/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class JavaProposalProvider extends AbstractJavaProposalProvider {
}
