/**
 * generated by Xtext
 */
package org.sourcepit.java.validation;

import org.sourcepit.java.validation.AbstractJavaValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class JavaValidator extends AbstractJavaValidator {
}
