/*
 * generated by Xtext
 */
package org.sourcepit.java.expressions.ui.contentassist

import org.sourcepit.java.expressions.ui.contentassist.AbstractExpressionsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ExpressionsProposalProvider extends AbstractExpressionsProposalProvider {
}
