/*
 * generated by Xtext
 */
package org.sourcepit.java.expressions.scoping

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
class ExpressionsScopeProvider extends org.sourcepit.java.literals.scoping.LiteralsScopeProvider {

}
