/*
 * generated by Xtext
 */

package org.sourcepit.java.type;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TypeRuntimeModule extends org.sourcepit.java.type.AbstractTypeRuntimeModule {

}
