/*
 * generated by Xtext
 */

package org.sourcepit.java.type;

/**
 * Initialization support for running Xtext languages
 * without equinox extension registry
 */
public class TypeStandaloneSetup extends TypeStandaloneSetupGenerated {

   public static void doSetup() {
      new TypeStandaloneSetup().createInjectorAndDoEMFRegistration();
   }
}
