/**
 * generated by Xtext
 */

package org.sourcepit.java.literals.validation;


/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class LiteralsValidator extends AbstractLiteralsValidator {
}
