/*
 * generated by Xtext
 */
package org.sourcepit.java.literals.ui.contentassist

import org.sourcepit.java.literals.ui.contentassist.AbstractLiteralsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LiteralsProposalProvider extends AbstractLiteralsProposalProvider {
}
