/*
 * generated by Xtext
 */

package org.sourcepit.java.literals.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LiteralsUiModule extends org.sourcepit.java.literals.ui.AbstractLiteralsUiModule {
   public LiteralsUiModule(AbstractUIPlugin plugin) {
      super(plugin);
   }
}
