/**
 * generated by Xtext
 */
package org.sourcepit.java.type.ui.contentassist;

import org.sourcepit.java.type.ui.contentassist.AbstractTypeProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class TypeProposalProvider extends AbstractTypeProposalProvider {
}
