/*
 * generated by Xtext
 */

package org.sourcepit.java.literals.validation;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractLiteralsValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

   @Override
   protected List<EPackage> getEPackages() {
      List<EPackage> result = new ArrayList<EPackage>();
      result.add(org.sourcepit.java.literals.literals.LiteralsPackage.eINSTANCE);
      return result;
   }
}
