/*
 * generated by Xtext
 */

package org.sourcepit.java.type.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.sourcepit.java.type.services.TypeGrammarAccess;

import com.google.inject.Inject;

public class TypeParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {

   @Inject
   private TypeGrammarAccess grammarAccess;

   @Override
   protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
      tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
   }

   @Override
   protected org.sourcepit.java.type.parser.antlr.internal.InternalTypeParser createParser(XtextTokenStream stream) {
      return new org.sourcepit.java.type.parser.antlr.internal.InternalTypeParser(stream, getGrammarAccess());
   }

   @Override
   protected String getDefaultRuleName() {
      return "Model";
   }

   public TypeGrammarAccess getGrammarAccess() {
      return this.grammarAccess;
   }

   public void setGrammarAccess(TypeGrammarAccess grammarAccess) {
      this.grammarAccess = grammarAccess;
   }

}
