/*
 * generated by Xtext
 */

package org.sourcepit.java.type.parser.antlr;

import java.io.InputStream;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TypeAntlrTokenFileProvider implements IAntlrTokenFileProvider {

   public InputStream getAntlrTokenFile() {
      ClassLoader classLoader = getClass().getClassLoader();
      return classLoader.getResourceAsStream("org/sourcepit/java/type/parser/antlr/internal/InternalType.tokens");
   }
}
