/*
 * generated by Xtext
 */

package org.sourcepit.java;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JavaRuntimeModule extends org.sourcepit.java.AbstractJavaRuntimeModule {

}
