/*
 * generated by Xtext
 */

package org.sourcepit.java;

/**
 * Initialization support for running Xtext languages
 * without equinox extension registry
 */
public class JavaStandaloneSetup extends JavaStandaloneSetupGenerated {

   public static void doSetup() {
      new JavaStandaloneSetup().createInjectorAndDoEMFRegistration();
   }
}
